var tipo_to_fa = {
    "p" : "pP",
    "b" : "bP",
    "m" : "bN",
    "bB": "bR",
    "bH": "bH",
    "pH": "pH",
    "m-": "vN",
    "v`": "vT",
    "f" : "fH",
    "v" : "vH",
    "vW": "vW",
    "tH": "tH",
    "dH": "dH",
    "t" : "sP",
    "d" : "zP",
    "n" : "zN",
    "r" : "zR",
    "r`": "zT",
    "s" : "sS",
    "z" : "zS",
    "sJ": "cS",
    "zJ": "jS",
    "sL": "sZ",
    "zL": "zZ",
    'r"': "zW",
    "l" : "zL",
    "t-": "lP",
    "d-": "rP",
    "n-": "rN",
    "rT": "rT",
    "sH": "$S",
    "zH": "nS",
    "s-": "lS",
    "z-": "rS",
    "r-": "rW",
    "l-": "rL",
    "c" : "cP",
    "gJ": "jP",
    "nJ": "jN",
    "cH": "cH",
    "jH": "jH",
    "j" : "jW",
    "jL": "jL",
    "k" : "kP",
    "g" : "gP",
    "nG": "gN",
    "x" : "kH",
    "gH": "gH",
    "w(": "gW",
    "gL": "gL",
    "q" : "qP",
    "g-": "GP",
    "nQ": "GN",
    "qR": "GR",
    "x-": "qH",
    "rH": "GH",
    "h+": "?H",
    "?H": "(H",
    "?" : "0K",
    "?+" : "?P",
    "h" : "hH",
    "hH": "?R",
    'h"': '"H',
    "?;": "(R",
    "xW": "xH",
    "w" : "wW",
    "jW": "yW",
    "*S": "lZ",
    
    "xH": "xS",
    "b!": "pQ",
    "d!": "tQ",
    "t!": "sQ",
    "r!": "lQ",
    "c!": "cQ",
    "b<": "bB",
    "d<": "zB",
    "c<": "jB",
    "g<": "gB",
    "q<": "GB",
    "l`": "z6",
    "l!": "z!",
        
    "a" : "a<",
    "e" : "e<",
    "i" : "i<",
    "o" : "o>",
    "u" : "u>",
    "y" : "u<",
    "A" : "a>",
    "E" : "E<",
    "I" : "I[",
    "O" : "O>",
    "U" : "U]",
    "Y" : "U[",
    
    "a)" : "A<",
    "e)" : "o<",
    "o(" : "e>",
    "u(" : "i>",
    "A)" : "A>",
    "E)" : "O<",
    "O(" : "E>",
    
    "a\"" : "@|",
    "e\"" : ":|",
    "i\"" : "i|",
    "o\"" : "o|",
    "i\"" : "i|",
    "u\"" : "u|",
    "E\"" : "E|",
    "e-" : "e|",
    "O\"" : "O|",
    "@" : "@[",
}

//https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
var fa_sound_set = new Set(['"H', '$S', '(H', '(R', '0K', ':|', '?H', '?P', '?R', '@[', '@|', 'A<', 'A>', 'E<', 'E>', 'E|', 'GB', 'GH', 'GN', 'GP', 'GR', 'I[', 'O<', 'O>', 'O|', 'U[', 'U]', 'a<', 'a>', 'bB', 'bH', 'bN', 'bP', 'bR', 'cH', 'cP', 'cQ', 'cS', 'dH', 'e<', 'e>', 'e|', 'fH', 'gB', 'gH', 'gL', 'gN', 'gP', 'gW', 'hH', 'i<', 'i>', 'i|', 'jB', 'jH', 'jL', 'jN', 'jP', 'jS', 'jW', 'kH', 'kP', 'lP', 'lQ', 'lS', 'lZ', 'nS', 'o<', 'o>', 'o|', 'pH', 'pP', 'pQ', 'qH', 'qP', 'rL', 'rN', 'rP', 'rS', 'rT', 'rW', 'sP', 'sQ', 'sS', 'sZ', 'tH', 'tQ', 'u<', 'u>', 'u|', 'vH', 'vN', 'vT', 'vW', 'wW', 'xH', 'xS', 'yW', 'z!', 'z6', 'zB', 'zL', 'zN', 'zP', 'zR', 'zS', 'zT', 'zW', 'zZ'])

var textarea_clicked = false;

var search_div = document.querySelector("div.search");
var search_text = document.querySelector("#search_text");

search_text.value = "Sound"
//https://stackoverflow.com/questions/17925577/change-text-color-with-javascript
search_text.style.color = "grey";

function on_focus () {
    if (!textarea_clicked) {
        search_text.value = ""
    }
    search_text.style.color = "black";
}